### ISSUE TITLE
Import todo app

### ISSUE THREAD

**Issue by biligunb** [Elbeg0406/Project-3#1]
- [x] import Todo app from previous project
- [x] Read [Хэрхэн САЙН ХӨГЖҮҮЛЭГЧ болох вэ?](https://medium.com/2b-1-better-2day/%D1%85%D1%8D%D1%80%D1%85%D1%8D%D0%BD-%D1%81%D0%B0%D0%B9%D0%BD-%D1%85%D3%A9%D0%B3%D0%B6%D2%AF%D2%AF%D0%BB%D1%8D%D0%B3%D1%87-%D0%B1%D0%BE%D0%BB%D0%BE%D1%85-%D0%B2%D1%8D-187c225c27cf)
- [x] Read [Shortcut](https://medium.com/2b-1-better-2day/shortcut-f18c64870518)
- [x] Read [Би хэрхэн ажилладаг вэ?](https://medium.com/2b-1-better-2day/%D0%B1%D0%B8-%D1%85%D1%8D%D1%80%D1%85%D1%8D%D0%BD-%D0%B0%D0%B6%D0%B8%D0%BB%D0%BB%D0%B0%D0%B4%D0%B0%D0%B3-%D0%B2%D1%8D-4a29872fe471)
- [x] Read [Junior to Senior](https://medium.com/2b-1-better-2day/junior-to-senior-962a8e75ddda)

**Comment by Elbeg0406** [comment]
Хэрхэн САЙН ХӨГЖҮҮЛЭГЧ болох вэ?
MVC — загварыг ойлгох
MVC - загвараар програмчлах нь илүү ойлгомжтой, эмх цэгцтэй байна

Coding Principle — дагаж мөрдөх
Эмц цэгцтэй кодчлох, хэрэггүй зүйл бичихгүй байх, аль болох амархан ойлгомжтой байх, хялбарчлах боломж байвал засаад сайжруулах

Comment — хэрэгцээт үед бичих
Байнга л comment бичих албагүй, эмх цэгцтэй ойлгомжтой бол бичих нь илүүц

Test code — бичиж занших
Бичсэн кодоо ахин дахин гараар шалгахыг автоматжуулж цаг хэмнэнэ, гараар шалгаснаас баталтгаатай, алдааг эрт мэднэ, тэрийгээ сайжруулах боломж олдоно

Linter — ашиглаж сурах
Eslint ашиглаж байсан шиг бичиглэлийн алдаа, хэрэглэгдэхгүй бичиглэлийг сануулах, автоматаар засах. 

Бусадтай сайн харилцах
Бусдын цагийг үрэхгүй тодорхой ойлгомжтой харилцах

Бусдаас тусламж авах
Тусламж хүсэхээс өмнө өөрөө асуудлын шийдлийг хайх, олох хүртэлээ үзээд болохгүй бол нэгтгэж байгаад юу юу судлаад болохгүй байгаа талаар асууж, харилцах, бусдын цагийг дэмий үрэхээр зүйл бүү асуу

Юмыг бүхлээр нь харах
Ямар нэгэн төсөл хийх гэж байгаа бол эхлээд тэрийгээ сайн ойлгох /ажиллах зарчим/. Нэг бүрчлэн төлөвлөх. Хийж байх явцдаа энэ яах ёстой вэ? юунд зориулж хийж байгаа вэ? гэх мэт асуулт гаргахгүй байх

Тасралтгүй суралцах
Ямар нэгэн зүйлийг бүгдийн мэдэх албагүй, зөвхөн өөрт хэрэгтэйг олж мэдэх, google, youtube, documentation хараад ойлгодог болох

**Comment by Elbeg0406** [comment]
Shortcut
Уншсан, зарим нь над шиг залхуу хүнд хэрэгтэй л юм

**Comment by Elbeg0406** [comment]
Би хэрхэн ажилладаг вэ?

Компаний ажилладаг зарчим, Билгүүн гэдэг хувь хүн талаас нь ойлголт авлаа

**Comment by Elbeg0406** [comment]
Junior to Senior

Юу вэ монголоор биш юм байна.
